apiVersion:  skaffold/v2beta29
kind: Config
metadata:
  name: example-app
build:
  artifacts:
    - image: example-app
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
  local:
    push: false

profiles:
  - name: local
    deploy:
      kustomize:
        paths: 
          - k8s/overlays/local
      kubeContext: k3d-k3s-local

  - name: test
    deploy:
      kustomize:
        paths: 
          - k8s/overlays/test
      kubeContext: k3d-k3s-local

portForward:
  - resourceType: service
    resourceName: example-app
    namespace: default
    port: 3000
    localPort: 3000