apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: example-app
build:
  artifacts:
    - image: example-app
      sync:
        manual:
        - src: 'src/*.js'
          dest: .

profiles:
  - name: local
    activation:
      - kubeContext: k3d-k3s-local
    manifests:
      kustomize:
        paths: 
          - k8s/overlays/local

  - name: test
    activation:
      - kubeContext: k3d-k3s-local
    manifests:
      kustomize:
        paths: 
          - k8s/overlays/test

portForward:
  - resourceType: service
    resourceName: example-app
    namespace: default
    port: 3000
    localPort: 3000