apiVersion: skaffold/v2beta9
kind: Config
build:
  artifacts:
    - image: registry.local:5000/example-app
      sync:
        manual:
        - src: 'src/**/*.js'
          dest: .
  local: {}
  insecureRegistries: 
    - registry.local:5000

profiles:
  - name: local
    deploy:
      kustomize:
        path: k8s/overlays/local
      kubeContext: k3s-local

  - name: test
    deploy:
      kustomize:
        path: k8s/overlays/test

portForward:
  - resourceType: service
    resourceName: example-app
    namespace: default
    port: 80
    localPort: 3000