apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: example-app
  labels:
    app: example-app
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80